### ISSUE TITLE
Unknown error on first start

### ISSUE THREAD

**Issue by dude513** [nibdo/bloben-app#118]
I followed https://docs.bloben.com/docs/intro, Bloben runs well, but I can't log in.

I used `admin` and `INITIAL_ADMIN_PASSWORD` password that I set in my `.env` file, but I am getting the following:

![image](https://github.com/nibdo/bloben-app/assets/123891835/da83eb33-f5f9-4b1c-8207-a390d9cb031e)

From docker logs there are no errors in `postgres` nor in `redis` containers, however there is something in `Bloben`:

```
PM2 log: Launching in no daemon mode
PM2 log: App [index:0] starting in -fork mode-
PM2 log: App [index:0] online
 Error: getaddrinfo ENOTFOUND databaseBloben # OR databaseBloben14 for docker-compose-pg14.yml file
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
   errno: -3008,
   code: 'ENOTFOUND',
   syscall: 'getaddrinfo',
   hostname: 'databaseBloben # OR databaseBloben14 for docker-compose-pg14.yml file'
 }
 [ioredis] Unhandled error event: Error: connect ETIMEDOUT
     at Socket.<anonymous> (/usr/app/api/node_modules/ioredis/built/Redis.js:168:41)
     at Object.onceWrapper (node:events:627:28)
     at Socket.emit (node:events:513:28)
     at Socket._onTimeout (node:net:550:8)
     at listOnTimeout (node:internal/timers:559:17)
     at processTimers (node:internal/timers:502:7)
 [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redisBloben
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
 [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redisBloben
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
 [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redisBloben
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
 [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND redisBloben
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
 2023-06-28T23:06:35: PM2 log: Launching in no daemon mode
 2023-06-28T23:06:35: PM2 log: App [index:0] starting in -fork mode-
 2023-06-28T23:06:35: PM2 log: App [index:0] online
 Error: getaddrinfo ENOTFOUND databaseBloben # OR databaseBloben14 for docker-compose-pg14.yml file
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
   errno: -3008,
   code: 'ENOTFOUND',
   syscall: 'getaddrinfo',
   hostname: 'databaseBloben # OR databaseBloben14 for docker-compose-pg14.yml file'
 }
```
The YML files are default from the repo, also I tried to rename `databaseBloben14` to something random as `databaseBloben14_2` as was mentioned in https://github.com/nibdo/bloben-app/issues/92 by @nibdo but it doesn't help and I am not sure if it supposed to help on the first install.

Just in case this is `docker-compose-pg14.yml`:

```
version: '3.7'

services:
  Bloben:
    image: 'bloben/app:latest'
    container_name: Bloben
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - '127.0.0.1:8081:80'
    restart: always

  databaseBloben14:
    image: 'postgres:14.6-bullseye'
    container_name: databaseBloben14
    env_file:
      - .env
    volumes:
      - databaseBlobenData14_2:/var/lib/postgresql/data
    ports:
      - '5432'
    restart: always

  redisBloben:
    image: redis:7.0.5-bullseye
    container_name: redisBloben
    volumes:
      - redisBlobenData:/data
    ports:
      - '6379'
    restart: always
#
#
volumes:
  databaseBlobenData14_2:
    name: databaseBlobenData14_2
  redisBlobenData:
    name: redisBlobenData
```

This is `docker-compose.yml`:

```
version: '3.7'

services:
  Bloben:
    image: 'bloben/app:latest'
    container_name: Bloben
    volumes:
      - ./logs:/logs
    env_file:
      - .env
    ports:
      - '127.0.0.1:8081:80'
    restart: always

  databaseBloben:
    image: 'postgres:13.9-bullseye'
    container_name: databaseBloben
    env_file:
      - .env
    volumes:
      - databaseBlobenData:/var/lib/postgresql/data
    ports:
      - '5432'
    restart: always

  redisBloben:
    image: redis:7.0.5-bullseye
    container_name: redisBloben
    volumes:
      - redisBlobenData:/data
    ports:
      - '6379'
    restart: always
#
#
volumes:
  databaseBlobenData:
    name: databaseBlobenData
  redisBlobenData:
    name: redisBlobenData
``` 
What I am missing?
