### ISSUE TITLE
Unable to add CalDavAccount

### ISSUE THREAD

**Issue by DominikSadko** [nibdo/bloben-app#40]
Error appears in console when trying to add account:
`POST http://localhost/api/v1/caldav-accounts 409 (Conflict)`

Env config:
```
NODE_ENV=production
HOST=localhost
PORT=8081

DB_HOST=databaseBloben
DB_PORT=5432
DB_USERNAME=bloben
DB_DATABASE=bloben_api
DB_CONNECTION=postgres
DB_SYNCHRONIZE=true
DB_LOGGING=false
DB_ENTITIES=usr/app/api/build/data/entity/*.js
DB_ENTITIES_DIR=usr/app/api/build/data/entity
DB_MIGRATIONS=usr/app/api/build/data/migrations/*.js

## Use same password for database for DB_PASSWORD and POSTGRES_PASSWORD
DB_PASSWORD=CHANGE_ME
POSTGRES_PASSWORD=CHANGE_ME

SESSION_SECRET=CHANGE_ME
OTP_SECRET=CHANGE_ME
INITIAL_ADMIN_PASSWORD=CHANGE_ME # your login password for admin account

REDIS_HOST=redisBloben
REDIS_PORT=6379

POSTGRES_DB=bloben_api
POSTGRES_USER=bloben

APP_DOMAIN=localhost

ENCRYPTION_PASSWORD=

SMTP_PORT=
SMTP_HOST=
SMTP_EMAIL=
SMTP_USERNAME=
SMTP_PASSWORD=
```

Server Docker Compose:
```
  caldavServer:
    image: ckulka/baikal:nginx
    container_name: caldavServer
    ports:
      - '8082:80'
    restart: always
```

Btw. what is "APP_DOMAIN"? In documentation is just mentioned "Your domain". Domain to caldav server? Domain to bloben?
