### ISSUE TITLE
[BUG] Cannot create new calendar for Radicale backend

### ISSUE THREAD

**Issue by palitu** [nibdo/bloben-app#50]
@[albsch](https://github.com/albsch) and I both have errors creating new calendars from Bloben, connecting to a Radicale server.

@nibdo , i am happy to create an account for you to connect to on my server, or share the docker-compose details for you to test against.

cheers

**Comment by nibdo** [comment]
Thank you, I will probably need to check also system/radicale server logs, so it would be better if I set up it on my infrastructure. 

I think I used this https://github.com/tomsquest/docker-radicale before for some small testing, but if you will share your docker-compose, it might be helpful. :) 

Thank you

**Comment by palitu** [comment]
I used Toms, but the simplified one, which is proxied by Nginx Proxy Manager.

```
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - 5232:5232
    restart: unless-stopped
    volumes:
      - ./radicale/data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```
