### ISSUE TITLE
Can't login to admin pannel

### ISSUE THREAD

**Issue by tiritibambix** [nibdo/bloben-app#92]
Hello there. Hope you're doing well :)

I've been willing to make a clean install since I've been messing around with my servers and you provided a new docker-compose.

I've followed the docs, but I can't log in to the admin pannel : ```Unknown error```

Here are my docker-compose and my .env just in case. I can't put my finger on the problem...

```
DB_HOST=databaseBloben14
DB_PORT=5432
DB_USERNAME=bloben
DB_DATABASE=bloben_api
DB_CONNECTION=postgres
DB_SYNCHRONIZE=true
DB_LOGGING=false
DB_ENTITIES=usr/app/api/build/data/entity/*.js
DB_ENTITIES_DIR=usr/app/api/build/data/entity
DB_MIGRATIONS=usr/app/api/build/data/migrations/*.js

## Use same password for database for DB_PASSWORD and POSTGRES_PASSWORD
DB_PASSWORD=SOMEPASSWD
POSTGRES_PASSWORD=SOMEPASSWD

SESSION_SECRET=MYSESSIONSECRET
OTP_SECRET=MYOPTSECRET
# your login password for admin account
INITIAL_ADMIN_PASSWORD=myadminpasswd

REDIS_HOST=redisBloben
REDIS_PORT=6379

POSTGRES_DB=bloben_api
POSTGRES_USER=bloben

APP_DOMAIN=bloben.mydomain.ltd

SMTP_PORT=myport
SMTP_HOST=myhost
SMTP_EMAIL=myemail
SMTP_USERNAME=myusername
SMTP_PASSWORD=mypassword
```

```
version: '3.7'

services:
  Bloben:
    image: 'bloben/app:latest'
    container_name: Bloben
    volumes:
      - /srv/Files/Bloben/logs:/logs
    env_file:
      - .env
    ports:
      - '8081:80'
    restart: always

  databaseBloben14:
    image: 'postgres:14.5-bullseye'
    container_name: databaseBloben14
    env_file:
      - .env
    volumes:
      - /srv/Files/Bloben/databaseBlobenData14:/var/lib/postgresql/data
    ports:
      - '5432'
    restart: always

  redisBloben:
    image: redis:7.0.5-bullseye
    container_name: redisBloben
    volumes:
      - /srv/Files/Bloben/redisBlobenData:/data
    ports:
      - '6379'
    restart: always
#
#
volumes:
  databaseBlobenData14:
    name: databaseBlobenData14
  redisBlobenData:
    name: redisBlobenData
```

I wanted to try and contact you via slack like before but can't find the address again...
